"""Write a scene config from a :class:`SceneSpec`.

A spec derives a scene's geometry; a config is how the simulator is told about it.
This is the bridge, and it is the reason the two shipped configs can stay exactly
as they are: a new layout is a spec plus one command, not a hand-copied config whose
numbers nobody can re-derive.

The *tuning* comes from a base config, because the spec deliberately does not derive
it -- gains, contact parameters and wall heights were chosen and measured, and
pretending otherwise would be the kind of invented formula the spec exists to
avoid.  The *geometry* comes from the spec, and it overwrites whatever the base had
for those keys, including removing a key the spec no longer produces (a two-box
base asked for one box must not keep its spare).

    python scripts/generate_scene_config.py --base configs/cookie_two_box_batch.yaml \\
        --boxes 3 --queue-gap 0.160 --output configs/generated/cookie_three_box.yaml

The output says at the top that it is generated, and prints the spec's derivation so
a reviewer sees what was decided and not only what was written.
"""

from __future__ import annotations

import argparse
from dataclasses import replace
from pathlib import Path

import yaml

from a3_dual_arm_sim.scene_spec import SceneSpec, two_box_spec

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BASE = ROOT / "configs" / "cookie_two_box_batch.yaml"

#: Keys the derivation owns.  Dropped from the base before the derived values go in,
#: so a spec that produces fewer boxes than its base cannot leave a stale box behind.
DERIVED_KEYS = (
    "source_bin_center_m",
    "source_bin_half_size_m",
    "target_bin_half_size_m",
    "target_bin_world_position_m",
    "spare_target_bin_world_position_m",
    "queue_target_bin_world_positions_m",
    "target_slots_local_m",
    "cookie_source_positions_m",
)

HEADER = """\
# GENERATED by scripts/generate_scene_config.py -- edit the spec, not this file.
#
# A lane of {boxes} boxes, filled one at a time: the station box is filled, pushed
# one {pitch:.0f} mm pitch further out, and the queue behind it advances.  The geometry
# is derived from `SceneSpec`; the tuning below is inherited from
# {base}.
#
# The queue gap is {gap:.0f} mm, which is wider than the {pitch:.0f} mm push pitch on purpose: the
# queue's own y range can close {closing:.0f} mm between two neighbours before any fill
# happens, so a lane laid out at the push pitch would exhaust its redraws.
"""


def render_config(base: Path, spec: SceneSpec) -> str:
    """The config text for ``spec``, with ``base``'s tuning and the spec's geometry.

    A function rather than a block inside :func:`main`, because the test that pins a
    committed config against its spec has to run the same code the command does --
    otherwise the two can drift and the test would not notice.
    """

    base_raw = yaml.safe_load(base.read_text(encoding="utf-8")) or {}
    cookie = dict(base_raw.get("cookie_transfer", {}))
    for key in DERIVED_KEYS:
        cookie.pop(key, None)
    derived = spec.derive_config()
    cookie.update(derived)
    # A lane of one is not a lane, and a stale spare left in the config would build a
    # box the spec never placed.  `derive_config` already decided which lane keys
    # exist, so this is where the base's opinion is overruled by the spec's.
    for key in ("spare_target_bin_world_position_m", "queue_target_bin_world_positions_m"):
        if key not in derived:
            cookie.pop(key, None)
    base_raw["cookie_transfer"] = cookie

    # The queue's closing movement, from the base's own spare y range: the widest a
    # neighbour can move towards the one in front, plus the widest that one can move
    # back.  Read rather than assumed, so the header states what this file really has.
    ranges = base_raw.get("randomization", {})
    spare_y = ranges.get("spare_bin_y_m", [0.0, 0.0])
    closing = abs(float(spare_y[0])) + abs(float(spare_y[1]))

    body = yaml.safe_dump(base_raw, sort_keys=False, default_flow_style=None, width=100)
    try:
        shown_base: object = base.relative_to(ROOT)
    except ValueError:
        shown_base = base
    header = HEADER.format(
        boxes=spec.boxes,
        pitch=spec.lane_pitch * 1000,
        gap=spec.queue_gap * 1000,
        closing=closing * 1000,
        base=shown_base,
    )
    return header + "\n" + body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--base", type=Path, default=DEFAULT_BASE)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--boxes", type=int, default=3)
    parser.add_argument("--per-grasp", type=int, default=5)
    parser.add_argument("--capacity", type=int, default=10)
    parser.add_argument("--source-cookies", type=int, default=80)
    parser.add_argument("--target-columns", type=int, default=2)
    parser.add_argument("--source-columns", type=int, default=4)
    parser.add_argument("--station-x", type=float, default=None)
    parser.add_argument("--station-y", type=float, default=None)
    parser.add_argument("--queue-gap", type=float, default=None)
    parser.add_argument("--lane-pitch", type=float, default=None)
    parser.add_argument(
        "--dry-run", action="store_true", help="print the derivation, write nothing"
    )
    args = parser.parse_args()

    # The relay's spec is the starting point because a lane is what this generates:
    # its station, its box margin and its queue are the ones that have been measured.
    spec = two_box_spec()
    spec = replace(
        spec,
        boxes=args.boxes,
        per_grasp=args.per_grasp,
        box_capacity=args.capacity,
        source_cookies=args.source_cookies,
        target_columns=args.target_columns,
        source_columns=args.source_columns,
        queue_gap_m=args.queue_gap,
        lane_pitch_m=args.lane_pitch,
        **({"station_x_m": args.station_x} if args.station_x is not None else {}),
        **({"station_y_m": args.station_y} if args.station_y is not None else {}),
    )
    spec.validate()
    print(spec.describe())

    base_raw = yaml.safe_load(args.base.read_text(encoding="utf-8")) or {}
    cookie = dict(base_raw.get("cookie_transfer", {}))
    for key in DERIVED_KEYS:
        cookie.pop(key, None)
    derived = spec.derive_config()
    cookie.update(derived)
    # A lane of one is not a lane, and a stale spare left in the config would build a
    # box the spec never placed.  `derive_config` already decided which lane keys
    # exist, so this is where the base's opinion is overruled by the spec's.
    for key in ("spare_target_bin_world_position_m", "queue_target_bin_world_positions_m"):
        if key not in derived:
            cookie.pop(key, None)
    base_raw["cookie_transfer"] = cookie

    # The queue's closing movement, from the base's own spare y range: the widest a
    # neighbour can move towards the one in front, plus the widest that one can move
    # back.  Read rather than assumed, so the header states what this file really has.
    ranges = base_raw.get("randomization", {})
    spare_y = ranges.get("spare_bin_y_m", [0.0, 0.0])
    closing = abs(float(spare_y[0])) + abs(float(spare_y[1]))

    body = yaml.safe_dump(base_raw, sort_keys=False, default_flow_style=None, width=100)
    header = HEADER.format(
        boxes=spec.boxes,
        pitch=spec.lane_pitch * 1000,
        gap=spec.queue_gap * 1000,
        closing=closing * 1000,
        base=args.base.relative_to(ROOT) if args.base.is_relative_to(ROOT) else args.base,
    )
    if args.dry_run:
        print()
        print(header)
        print(body)
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header + "\n" + body, encoding="utf-8")
    print(f"\nwrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
